/*
 * WhereTo API
 * WhereTo API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.KeyAndPasswordVM;
import io.swagger.client.model.ManagedUserVM;
import io.swagger.client.model.PasswordChangeDTO;
import io.swagger.client.model.UserDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccountResourceApi
 */
@Ignore
public class AccountResourceApiTest {

    private final AccountResourceApi api = new AccountResourceApi();

    /**
     * activateAccount
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void activateAccountUsingGETTest() throws ApiException {
        String key = null;
        api.activateAccountUsingGET(key);

        // TODO: test validations
    }
    /**
     * changePassword
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void changePasswordUsingPOSTTest() throws ApiException {
        PasswordChangeDTO body = null;
        api.changePasswordUsingPOST(body);

        // TODO: test validations
    }
    /**
     * finishPasswordReset
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void finishPasswordResetUsingPOSTTest() throws ApiException {
        KeyAndPasswordVM body = null;
        api.finishPasswordResetUsingPOST(body);

        // TODO: test validations
    }
    /**
     * getAccount
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccountUsingGETTest() throws ApiException {
        UserDTO response = api.getAccountUsingGET();

        // TODO: test validations
    }
    /**
     * isAuthenticated
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void isAuthenticatedUsingGETTest() throws ApiException {
        String response = api.isAuthenticatedUsingGET();

        // TODO: test validations
    }
    /**
     * registerAccount
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void registerAccountUsingPOSTTest() throws ApiException {
        ManagedUserVM body = null;
        api.registerAccountUsingPOST(body);

        // TODO: test validations
    }
    /**
     * requestPasswordReset
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void requestPasswordResetUsingPOSTTest() throws ApiException {
        String body = null;
        api.requestPasswordResetUsingPOST(body);

        // TODO: test validations
    }
    /**
     * saveAccount
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void saveAccountUsingPOSTTest() throws ApiException {
        UserDTO body = null;
        api.saveAccountUsingPOST(body);

        // TODO: test validations
    }
}
