/*
 * WhereTo API
 * WhereTo API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.DisplayDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DisplayResourceApi
 */
@Ignore
public class DisplayResourceApiTest {

    private final DisplayResourceApi api = new DisplayResourceApi();

    /**
     * createDisplay
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createDisplayUsingPOSTTest() throws ApiException {
        DisplayDTO body = null;
        DisplayDTO response = api.createDisplayUsingPOST(body);

        // TODO: test validations
    }
    /**
     * deleteDisplay
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteDisplayUsingDELETETest() throws ApiException {
        Long id = null;
        api.deleteDisplayUsingDELETE(id);

        // TODO: test validations
    }
    /**
     * getAllDisplays
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllDisplaysUsingGETTest() throws ApiException {
        Boolean eagerload = null;
        Integer page = null;
        Integer size = null;
        List<String> sort = null;
        List<DisplayDTO> response = api.getAllDisplaysUsingGET(eagerload, page, size, sort);

        // TODO: test validations
    }
    /**
     * getDisplay
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDisplayUsingGETTest() throws ApiException {
        Long id = null;
        DisplayDTO response = api.getDisplayUsingGET(id);

        // TODO: test validations
    }
    /**
     * updateDisplay
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateDisplayUsingPUTTest() throws ApiException {
        DisplayDTO body = null;
        DisplayDTO response = api.updateDisplayUsingPUT(body);

        // TODO: test validations
    }
}
