/*
 * WhereTo API
 * WhereTo API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.InteresDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InteresResourceApi
 */
@Ignore
public class InteresResourceApiTest {

    private final InteresResourceApi api = new InteresResourceApi();

    /**
     * createInteres
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createInteresUsingPOSTTest() throws ApiException {
        InteresDTO body = null;
        InteresDTO response = api.createInteresUsingPOST(body);

        // TODO: test validations
    }
    /**
     * deleteInteres
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteInteresUsingDELETETest() throws ApiException {
        Long id = null;
        api.deleteInteresUsingDELETE(id);

        // TODO: test validations
    }
    /**
     * getAllInteres
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllInteresUsingGETTest() throws ApiException {
        Integer page = null;
        Integer size = null;
        List<String> sort = null;
        List<InteresDTO> response = api.getAllInteresUsingGET(page, size, sort);

        // TODO: test validations
    }
    /**
     * getInteres
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getInteresUsingGETTest() throws ApiException {
        Long id = null;
        InteresDTO response = api.getInteresUsingGET(id);

        // TODO: test validations
    }
    /**
     * updateInteres
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateInteresUsingPUTTest() throws ApiException {
        InteresDTO body = null;
        InteresDTO response = api.updateInteresUsingPUT(body);

        // TODO: test validations
    }
}
