/*
 * WhereTo API
 * WhereTo API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.TagDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TagResourceApi
 */
@Ignore
public class TagResourceApiTest {

    private final TagResourceApi api = new TagResourceApi();

    /**
     * createTag
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTagUsingPOSTTest() throws ApiException {
        TagDTO body = null;
        TagDTO response = api.createTagUsingPOST(body);

        // TODO: test validations
    }
    /**
     * deleteTag
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteTagUsingDELETETest() throws ApiException {
        Long id = null;
        api.deleteTagUsingDELETE(id);

        // TODO: test validations
    }
    /**
     * getAllTags
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllTagsUsingGETTest() throws ApiException {
        Integer page = null;
        Integer size = null;
        List<String> sort = null;
        List<TagDTO> response = api.getAllTagsUsingGET(page, size, sort);

        // TODO: test validations
    }
    /**
     * getTag
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTagUsingGETTest() throws ApiException {
        Long id = null;
        TagDTO response = api.getTagUsingGET(id);

        // TODO: test validations
    }
    /**
     * updateTag
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateTagUsingPUTTest() throws ApiException {
        TagDTO body = null;
        TagDTO response = api.updateTagUsingPUT(body);

        // TODO: test validations
    }
}
