/*
 * WhereTo API
 * WhereTo API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.User;
import io.swagger.client.model.UserDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserResourceApi
 */
@Ignore
public class UserResourceApiTest {

    private final UserResourceApi api = new UserResourceApi();

    /**
     * createUser
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createUserUsingPOSTTest() throws ApiException {
        UserDTO body = null;
        User response = api.createUserUsingPOST(body);

        // TODO: test validations
    }
    /**
     * deleteUser
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteUserUsingDELETETest() throws ApiException {
        String login = null;
        api.deleteUserUsingDELETE(login);

        // TODO: test validations
    }
    /**
     * getAllUsers
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllUsersUsingGETTest() throws ApiException {
        Integer page = null;
        Integer size = null;
        List<String> sort = null;
        List<UserDTO> response = api.getAllUsersUsingGET(page, size, sort);

        // TODO: test validations
    }
    /**
     * getAuthorities
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAuthoritiesUsingGETTest() throws ApiException {
        List<String> response = api.getAuthoritiesUsingGET();

        // TODO: test validations
    }
    /**
     * getUser
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserUsingGETTest() throws ApiException {
        String login = null;
        UserDTO response = api.getUserUsingGET(login);

        // TODO: test validations
    }
    /**
     * updateUser
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateUserUsingPUTTest() throws ApiException {
        UserDTO body = null;
        UserDTO response = api.updateUserUsingPUT(body);

        // TODO: test validations
    }
}
