/*
 * WhereTo API
 * WhereTo API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.UserDetailsDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserDetailsResourceApi
 */
@Ignore
public class UserDetailsResourceApiTest {

    private final UserDetailsResourceApi api = new UserDetailsResourceApi();

    /**
     * createUserDetails
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createUserDetailsUsingPOSTTest() throws ApiException {
        UserDetailsDTO body = null;
        UserDetailsDTO response = api.createUserDetailsUsingPOST(body);

        // TODO: test validations
    }
    /**
     * deleteUserDetails
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteUserDetailsUsingDELETETest() throws ApiException {
        Long id = null;
        api.deleteUserDetailsUsingDELETE(id);

        // TODO: test validations
    }
    /**
     * getAllUserDetails
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllUserDetailsUsingGETTest() throws ApiException {
        Boolean eagerload = null;
        Integer page = null;
        Integer size = null;
        List<String> sort = null;
        List<UserDetailsDTO> response = api.getAllUserDetailsUsingGET(eagerload, page, size, sort);

        // TODO: test validations
    }
    /**
     * getUserDetailsByUser
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserDetailsByUserUsingGETTest() throws ApiException {
        String login = null;
        UserDetailsDTO response = api.getUserDetailsByUserUsingGET(login);

        // TODO: test validations
    }
    /**
     * getUserDetails
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserDetailsUsingGETTest() throws ApiException {
        Long id = null;
        UserDetailsDTO response = api.getUserDetailsUsingGET(id);

        // TODO: test validations
    }
    /**
     * updateUserDetails
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateUserDetailsUsingPUTTest() throws ApiException {
        UserDetailsDTO body = null;
        UserDetailsDTO response = api.updateUserDetailsUsingPUT(body);

        // TODO: test validations
    }
}
