/*
 * WhereTo API
 * WhereTo API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.JWTToken;
import io.swagger.client.model.LoginVM;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserJwtControllerApi
 */
@Ignore
public class UserJwtControllerApiTest {

    private final UserJwtControllerApi api = new UserJwtControllerApi();

    /**
     * authorize
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void authorizeUsingPOSTTest() throws ApiException {
        LoginVM body = null;
        JWTToken response = api.authorizeUsingPOST(body);

        // TODO: test validations
    }
}
