/*
 * Locations API
 * This document describes the Kiwi.com locations search API.  **Locations** is a simple API used to search, suggest and resolve locations in various situations.  ## Contact us In case you cannot find what you are looking for in this document please contact us directly at **[tequila-support@kiwi.com](mailto:tequila-support@kiwi.com)**.  **The responses are G-zipped and need to be unpacked (response header Content-Encoding: gzip).**
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Meta;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponse2001
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-05-10T23:04:34.003+02:00[Europe/Ljubljana]")public class InlineResponse2001 {

  @SerializedName("hashtags")
  private List<String> hashtags = null;

  @SerializedName("meta")
  private Meta meta = null;
  public InlineResponse2001 hashtags(List<String> hashtags) {
    this.hashtags = hashtags;
    return this;
  }

  public InlineResponse2001 addHashtagsItem(String hashtagsItem) {
    if (this.hashtags == null) {
      this.hashtags = new ArrayList<String>();
    }
    this.hashtags.add(hashtagsItem);
    return this;
  }

  /**
  * array of top hashtags for destinations
  * @return hashtags
  **/
  @Schema(example = "[]", description = "array of top hashtags for destinations")
  public List<String> getHashtags() {
    return hashtags;
  }
  public void setHashtags(List<String> hashtags) {
    this.hashtags = hashtags;
  }
  public InlineResponse2001 meta(Meta meta) {
    this.meta = meta;
    return this;
  }

  

  /**
  * Get meta
  * @return meta
  **/
  @Schema(description = "")
  public Meta getMeta() {
    return meta;
  }
  public void setMeta(Meta meta) {
    this.meta = meta;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2001 inlineResponse2001 = (InlineResponse2001) o;
    return Objects.equals(this.hashtags, inlineResponse2001.hashtags) &&
        Objects.equals(this.meta, inlineResponse2001.meta);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(hashtags, meta);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2001 {\n");
    
    sb.append("    hashtags: ").append(toIndentedString(hashtags)).append("\n");
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
