/*
 * WhereTo API
 * WhereTo API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.TagDTO;
import io.swagger.client.model.UserDetailsDTO;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * DisplayDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-05-11T13:57:16.194+02:00[Europe/Ljubljana]")public class DisplayDTO {

  @SerializedName("id")
  private Long id = null;

  @SerializedName("image")
  private String image = null;

  @SerializedName("imageContentType")
  private String imageContentType = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("showeds")
  private List<UserDetailsDTO> showeds = null;

  @SerializedName("tags")
  private List<TagDTO> tags = null;
  public DisplayDTO id(Long id) {
    this.id = id;
    return this;
  }

  

  /**
  * Get id
  * @return id
  **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }
  public void setId(Long id) {
    this.id = id;
  }
  public DisplayDTO image(String image) {
    this.image = image;
    return this;
  }

  

  /**
  * Get image
  * @return image
  **/
  @Schema(description = "")
  public String getImage() {
    return image;
  }
  public void setImage(String image) {
    this.image = image;
  }
  public DisplayDTO imageContentType(String imageContentType) {
    this.imageContentType = imageContentType;
    return this;
  }

  

  /**
  * Get imageContentType
  * @return imageContentType
  **/
  @Schema(description = "")
  public String getImageContentType() {
    return imageContentType;
  }
  public void setImageContentType(String imageContentType) {
    this.imageContentType = imageContentType;
  }
  public DisplayDTO name(String name) {
    this.name = name;
    return this;
  }

  

  /**
  * Get name
  * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  public DisplayDTO showeds(List<UserDetailsDTO> showeds) {
    this.showeds = showeds;
    return this;
  }

  public DisplayDTO addShowedsItem(UserDetailsDTO showedsItem) {
    if (this.showeds == null) {
      this.showeds = new ArrayList<UserDetailsDTO>();
    }
    this.showeds.add(showedsItem);
    return this;
  }

  /**
  * Get showeds
  * @return showeds
  **/
  @Schema(description = "")
  public List<UserDetailsDTO> getShoweds() {
    return showeds;
  }
  public void setShoweds(List<UserDetailsDTO> showeds) {
    this.showeds = showeds;
  }
  public DisplayDTO tags(List<TagDTO> tags) {
    this.tags = tags;
    return this;
  }

  public DisplayDTO addTagsItem(TagDTO tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<TagDTO>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
  * Get tags
  * @return tags
  **/
  @Schema(description = "")
  public List<TagDTO> getTags() {
    return tags;
  }
  public void setTags(List<TagDTO> tags) {
    this.tags = tags;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DisplayDTO displayDTO = (DisplayDTO) o;
    return Objects.equals(this.id, displayDTO.id) &&
        Objects.equals(this.image, displayDTO.image) &&
        Objects.equals(this.imageContentType, displayDTO.imageContentType) &&
        Objects.equals(this.name, displayDTO.name) &&
        Objects.equals(this.showeds, displayDTO.showeds) &&
        Objects.equals(this.tags, displayDTO.tags);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, image, imageContentType, name, showeds, tags);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DisplayDTO {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    imageContentType: ").append(toIndentedString(imageContentType)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    showeds: ").append(toIndentedString(showeds)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
