/*
 * WhereTo API
 * WhereTo API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * InteresDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-05-11T13:57:16.194+02:00[Europe/Ljubljana]")public class InteresDTO {

  @SerializedName("id")
  private Long id = null;

  @SerializedName("tagId")
  private Long tagId = null;

  @SerializedName("tagName")
  private String tagName = null;

  @SerializedName("userId")
  private Long userId = null;

  @SerializedName("userName")
  private String userName = null;

  @SerializedName("value")
  private Integer value = null;
  public InteresDTO id(Long id) {
    this.id = id;
    return this;
  }

  

  /**
  * Get id
  * @return id
  **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }
  public void setId(Long id) {
    this.id = id;
  }
  public InteresDTO tagId(Long tagId) {
    this.tagId = tagId;
    return this;
  }

  

  /**
  * Get tagId
  * @return tagId
  **/
  @Schema(description = "")
  public Long getTagId() {
    return tagId;
  }
  public void setTagId(Long tagId) {
    this.tagId = tagId;
  }
  public InteresDTO tagName(String tagName) {
    this.tagName = tagName;
    return this;
  }

  

  /**
  * Get tagName
  * @return tagName
  **/
  @Schema(description = "")
  public String getTagName() {
    return tagName;
  }
  public void setTagName(String tagName) {
    this.tagName = tagName;
  }
  public InteresDTO userId(Long userId) {
    this.userId = userId;
    return this;
  }

  

  /**
  * Get userId
  * @return userId
  **/
  @Schema(description = "")
  public Long getUserId() {
    return userId;
  }
  public void setUserId(Long userId) {
    this.userId = userId;
  }
  public InteresDTO userName(String userName) {
    this.userName = userName;
    return this;
  }

  

  /**
  * Get userName
  * @return userName
  **/
  @Schema(description = "")
  public String getUserName() {
    return userName;
  }
  public void setUserName(String userName) {
    this.userName = userName;
  }
  public InteresDTO value(Integer value) {
    this.value = value;
    return this;
  }

  

  /**
  * Get value
  * @return value
  **/
  @Schema(required = true, description = "")
  public Integer getValue() {
    return value;
  }
  public void setValue(Integer value) {
    this.value = value;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InteresDTO interesDTO = (InteresDTO) o;
    return Objects.equals(this.id, interesDTO.id) &&
        Objects.equals(this.tagId, interesDTO.tagId) &&
        Objects.equals(this.tagName, interesDTO.tagName) &&
        Objects.equals(this.userId, interesDTO.userId) &&
        Objects.equals(this.userName, interesDTO.userName) &&
        Objects.equals(this.value, interesDTO.value);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, tagId, tagName, userId, userName, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InteresDTO {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    tagId: ").append(toIndentedString(tagId)).append("\n");
    sb.append("    tagName: ").append(toIndentedString(tagName)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
